DEFAULT_POPULATION_SIZE = 500
DEFAULT_N_GENERATIONS = 600
DEFAULT_CROSSOVER_RATE = 0.5
DEFAULT_MUTATION_RATE = 0.1
DEFAULT_RETENTION_RATE = 0.6
DEFAULT_RANDOM_SELECTION_RATE = 0.05
DEFAULT_GOL_NUM_STEPS = 5
DEFAULT_WOLFRAM_NUM_STEPS = 19
DEFAULT_CALLBACK_INTERVAL = 100

CA_NAME_GAME_OF_LIFE = "game_of_life"
CA_NAME_WOLFRAM_CA = "wolfram_ca"
FITNESS_FUNCTION_MAE = "mae"
FITNESS_FUNCTION_STRUCTURAL_SIMILARITY = "structural_similarity"
