DEFAULT_POPULATION_SIZE = 1000
DEFAULT_N_GENERATIONS = 500
DEFAULT_CROSSOVER_RATE = 0.5
DEFAULT_MUTATION_RATE = 0.1
DEFAULT_RETENTION_RATE = 0.6
DEFAULT_RANDOM_SELECTION_RATE = 0.05
DEFAULT_GOL_NUM_STEPS = 5
DEFAULT_WOLFRAM_NUM_STEPS = 19